### ISSUE TITLE
LOGS_PATH env var should be DEBUGLOG

### ISSUE THREAD

**Issue by earnubs** [canonical-websites/build.snapcraft.io#100]
Suggest we follow the patterns defined in Talisker:
http://talisker.readthedocs.io/en/latest/logging.html#debug-logging

So the env var here https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/server/logging/index.js#L10 should be DEBUGLOG

**Comment by cjwatson** [comment]
`LOGS_PATH` is a directory that holds multiple log files whose names are defined by parameters to `logging.getLogger`; `DEBUGLOG` is just the single debug log file.  So this will be a bit more involved than just a renaming.

The Talisker docs seem to imply that the default is just to log to stderr; I deliberately arranged to log to disk since I found having to pick log information out of the systemd journal on individual units to be extremely cumbersome.  We don't necessarily have to stick with exactly what we have now of course, but I think the ability for server code to easily dump things to different log files is pretty useful and worth preserving.  At some point we should probably check the exact behaviour of the Talisker code here, or of typical Python users of it.

**Comment by nottrobin** [comment]
It looks like this has stalled rather. It's not super clear to me what the real value of doing this work would be and based on Colin's comment I'm not sure if this is worth doing, given how many other issues we have to fix.

I'm going to close this now, but @cjwatson if you think this is in fact a priority please let me know and we can re-open this issue.
