### ISSUE TITLE
Research: Check all the project's dependencies can be encapsulated with Docker

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#1016]

**Comment by tbille** [comment]
I did a first Pull request to create a Dockerfile for the project: https://github.com/canonical-websites/build.snapcraft.io/pull/1020

But to deploy on Kubernetes we will need to change a few things on the project:

* BSI uses a 2 differents database depending on the environment:
  * sqlite for development
   * Postgre for staging and production
**Here we would need to remove the sqlite database so that we have the same database type than production**. This mean we will need to add a Postgre service in our run script.

* BSI uses memcache: **Same as database, add this service in our run script**
  * We also have stored secrets for memcache

On production and staging BSI is deployed as a juju charm. We need to find a way to understand how could we connect those services to our instance of k8s. Or migrate the data stored to a service that could be connected to our k8s.

Here is a document on how BSI is actually deployed: https://wiki.canonical.com/ProductStrategyTeam/WebDevelopment/build.snapcraft.io

**Comment by nottrobin** [comment]
> We need to find a way to understand how could we connect those services to our instance of k8s. Or migrate the data stored to a service that could be connected to our k8s.

To be able to deploy this on Kubernetes, ideally we need to remove the PostgreSQL database entirely. Per [the policy](https://wiki.canonical.com/InformationInfrastructure/IS/Kubernetes/Policy):

> Be largely stateless, i.e. not (include) a database

So we need some work to be done to migrate stateful parts of the app to an external service that we can talk to through an API.

> BSI uses memcache

My understanding is that we may use memcached in Kubernetes, as long as it's not to actually store persistent state. Is this the case? Is memcached just used for caching etc. and not for meaningful state?

> We also have stored secrets for memcache

These secrets would need to be migrated to being Kubernetes secrets that the app will then retrieve as environment variables.
