### ISSUE TITLE
build.snapcraft.io snap never gets built is snapcraft.yaml is not found when repo is added

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/build.snapcraft.io#1036]
@lucasrangit commented on [Thu Oct 26 2017](https://github.com/canonical-websites/tutorials.ubuntu.com/issues/387)

Steps to reproduce:

1. Fork any project on https://github.com
1. Crate branch with any name (e.g. "snapcraft")
1. Push a snapcraft.yaml for a project named `anything-$USERNAME`
1. Use https://build.snapcraft.io to add repository
1. https://build.snapcraft.io will fail to find a `snapcraft.yaml`
1. Change repository's default branch on GitHub
1. https://build.snapcraft.io eventually detects and finds `snapcraft.yaml` 
1. Observe that a build is never started

**Comment by bartaz** [comment]
Builds are automatically triggered in 2 situations:
1) when new repo is added, configured (has valid snapcraft.yaml) and name is registered via BSI - at the point of registering the name repo needs to have snapcraft.yaml for build to be triggered
2) on commit webhook from GH - if repo after a webhook trigger has snapcraft.yaml build is triggered by commit

It seems that changing default branch doesn't trigger webhook, which means we don't have a good way to detect that snapcraft.yaml was added (because there was no commit).
Of course when repo data is refreshed eventually it will show up as configured on My repos page of the user, but the sole fact that snapcraft.yaml exists is not enough (and shouldn't be enough) to trigger the build.

One way to fix this could be to defect repos that have registered name, have snapcraft.yaml but haven't been built yet and trigger builds for those.
The issue with such approach is that currently we load builds statuses asynchronously after repos build is loaded and we cannot really tell the difference between repos that have never been built and repos that we haven't loaded builds for yet.

The other way to work around that would be to at least allow user to trigger builds manually for such repo. Which right now is also not possible because repo page (where builds can be triggered) is not available until there are some builds already available.
