### ISSUE TITLE
Something went wrong when calling GitHub API

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1089]
## Summary

"Something went wrong when calling GitHub API" when registering a name

## Process

Add a new repo.
Click "Register name"

## Current and expected result

Expected it to register (it's already registered) and start building.
It gave me a GitHub API error.

## Screenshot

![image](https://user-images.githubusercontent.com/1841272/39814963-5c213f0e-538e-11e8-8e17-a248a963263f.png)

**Comment by bartaz** [comment]
Cannot reproduce this issue now, and also looking at the logs from last couple of days we didn't have any significant problems with GH API (apart from expected 404s, etc).

It's possible (looking at the error status code) that the issue was caused by exceeded GH API rate limit. We have already implemented fixes that should prevent that from happening, so hopefully this issue will not show up again.

If it does happen again feel free to reopen it.
