### ISSUE TITLE
Authentication failed. API rate limit exceeded for user ID 1841272.

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1090]
## Summary

Trying to use build.snapcraft.io and now I can't even login

## Process

visit build.snapcraft.io
login

## Current and expected result

Expected to get logged in and see my repos
Got an error "Authentication failed. API rate limit exceeded for user ID 1841272."

## Screenshot

![screenshot from 2018-05-10 14-59-34](https://user-images.githubusercontent.com/1841272/39873497-03c1ca56-5463-11e8-9075-879b711b5f14.png)

**Comment by bartaz** [comment]
GH API rate limit is 5000 requests per hour (per authenticated user) and we never had any issue with it being not enough.

But we may need to verify if we don't poll API too often (for example if user has many repos). Possibly some extensive reloading could have reached this limit.

As far as I remember GH clears rate limits every hour, so it should be back operational when it's cleared on GH side.

**Comment by bartaz** [comment]
I just had couple BSI tabs open with snapcrafters repos for less then an hour and it killed my GH rate as well.

I don't think we are calling GH API when polling for build statuses (which is the most frequent call), but it seems we do call it a lot when there are many repos.

**Comment by Lukewh** [comment]
Immediate fix:

- When a tab is not focused, stop polling.
- Show an overlay explaining the tab is paused, including a 'continue' CTA (just in case there's a delay when...)
- Resume polling on tab focus (and remove the overlay)

Longer term investigations and improvements:

- Audit calls to Github and optimize where possible
- Poll less frequently until a build is detected, increase polling then back off again when the build is complete.

**Comment by bartaz** [comment]
### Quick GH calls audit

On 'My repos' page we poll (currently every 30 seconds) for list of user snaps/repos and build status of these repos. Build status calls (even that there are lots of them) only call LP, so they don't add up to GH API rate limit.

Request for list of user repos consists of couple of parts:
- call for list of user GH orgs
- call for lists of user snaps (for GH user and all the orgs)
- call for branch and snapcraft.yaml data (for every repo on the list)

So in theory every time we request list of repos (including their config status) we would call GH multiple times (for each repo).
Fortunately these calls are memcached with timeout set for an hour (3600 sec). This means that for **most** of repos we only call GH for their snapcraft.yaml data once an hour.

It's 'most' and not 'every', it seems we only memcache data for repos that have snapcraft.yaml. If repo doesn't have snapcraft.yaml (is not configured) we don't memcache this result and we attempt looking for snapcraft.yaml every time we poll.
And because we try to find snapcraft.yaml in 3 possible locations inside the repo it means we make 3 calls to GH (just to find out snapcraft.yaml is not there).

3 requests every 30 seconds makes it 120 * 3 = 360 requests every hour. Doesn't seem much compared to 5000 requests GH rate limit. But if user has more then 10 not configured repos it grows up to over 3600 - which in addition to other GH requests (and possibly other tools that make requests to GH for user) this may quickly lead up to exceeding GH rate limit.

Hopefully disabling polling when page is in background (https://github.com/canonical-websites/build.snapcraft.io/pull/1099) will help with this issue.
Additionally we may need to consider memcaching also the fact that repository doesn't have snapcraft.yaml to reduce unnecessary GH API calls.

**Comment by Lukewh** [comment]
Good sleuthing Commissioner Gordon.

We could possibly back off if we don't find a snapcraft.yaml, or add a manual 'I've added a snapcraft.yaml, try and find it please' button in the UI?

**Comment by bartaz** [comment]
@Lukewh As far as I can see in the code snapcraft.yaml part of memcached is cleared on webhook push from GH. So as long as someone pushes snapcraft.yaml to GH (and has webhook properly set up), we should already be clearing up memcached and getting fresh data with next poll.

So it seems that the only missing part is actually memcaching the 'not configured' state.
