### ISSUE TITLE
maven build fails

### ISSUE THREAD

**Issue by jsseidel** [canonical-websites/build.snapcraft.io#1126]
## Summary

Added a new repo of mine (https://github.com/jsseidel/jgalaxian) to publish a game from a maven project. Compiles fine in 16.04/18.04, but won't finish building in the build.snapcraft.io build process.

The following is the tail end of the log. [Here is the entire build log](https://github.com/canonical-websites/build.snapcraft.io/files/2193514/build-278361.log).

```
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known: Unknown host repo.maven.apache.org: Name or service not known -> [Help 1]
```

## Process

Build the app manually wherever build.snapcraft.io does, I suppose, to see if the build will fail.

## Current and expected result

Build failure is what happens. Build success is what should happen.

**Comment by cjwatson** [comment]
Your problem is that your `override-build` definition overrides the default behaviour of snapcraft's maven plugin in a way that breaks its default handling of the network proxy whose use is required in Launchpad builds.

I think this `override-build` definition is unnecessary.  OpenJDK 8 is already the default in xenial, so builds on build.snapcraft.io will use it without you having to do anything special; and, if I'm reading the code correctly, snapcraft's maven plugin will already copy the resulting `*.jar` files to the install directory.  Can you try simply deleting the `override-build` and `build-packages` items from your `jgalaxian` part?

**Comment by cjwatson** [comment]
Also, if you need to do what a plugin does by default but also do some extra bits and pieces, then I believe the recommended way to do that is to call (e.g.) `snapcraftctl build` rather than trying to reimplement the plugin's behaviour.  See the [scriptlets documentation](https://docs.snapcraft.io/build-snaps/scriptlets).

**Comment by jsseidel** [comment]
Thanks for the info. I too took a look at the maven plugin and discovered that the basedir was being set to "jar", so the jar file was copied in there (e.g. /snap/jgalaxian/x2/jar). I think that tripped me up when I first created the snapcraft.yaml file, so I got impatient and overrode the build. I think you can call this issue closed. I will retry with the SnapStore.
