### ISSUE TITLE
Cannot build base snaps

### ISSUE THREAD

**Issue by slimjim777** [canonical-websites/build.snapcraft.io#1147]
## Summary

Base snaps need to be built using `sudo snapcraft` instead of `snapcraft`.

## Process

Using https://build.snapcraft.io/user/slimjim777/core18-ros as an example:
-  Building the snap locally using `sudo snapcraft`. This works.
- Try building using build.snapcraft.io and it fails.

## Current and expected result

The service does not seem to be aware of base snaps. It should be able to see that that snap is a base snap from the yaml and adjust accordingly

## Screenshot

https://build.snapcraft.io/user/slimjim777/core18-ros
https://build.snapcraft.io/user/slimjim777/core18-ros/329788

**Comment by cjwatson** [comment]
The "Illegal instruction" error that I see there isn't the sort of thing that would be fixed by running it under `sudo`; that sounds more like the base snap is using some CPU instruction that isn't implemented by the arm64 hardware in use on the builders.

Anyway, this sort of thing needs to be filed against [launchpad-buildd](https://bugs.launchpad.net/launchpad-buildd); build.snapcraft.io is just the frontend to that.  Please could you refile this there, and then close this issue?  Thanks.

**Comment by cjwatson** [comment]
Also, launchpad-buildd *already* runs snapcraft as root, so it's clearly not that.  There's a [bug](https://bugs.launchpad.net/launchpad-buildd/+bug/1702656) for running it as non-root.
