### ISSUE TITLE
App disappeared from my app list

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#1181]
## Summary

I need to trigger a build of atom, as there's been an upstream update. I went to build.snapcraft.io and logged in. Atom is no longer in the list. It certainly was, because I've built it numerous times.  I have had to re-add it again (which is spinning forever)...

![image](https://user-images.githubusercontent.com/1841272/49327372-c83a6f00-f558-11e8-9e0e-21000ea1e352.png)

## Process

I don't know how to reproduce this, but I do sometimes see apps gone from the list which should be there.

## Current and expected result

Visited build.snapcraft.io, logged in, expected to see all the applications I've added. Actually saw atom missing.

**Comment by bartaz** [comment]
I can confirm that I also don't see the snap on my list (while seeing other `snaprcrafters` repos).
The snap itself exists in launchpad: https://launchpad.net/~build.snapcraft.io/+snap/a327af41d53ecba7cdcf391f6b95c0cf-xenial and can be accessed directly: https://build.snapcraft.io/user/snapcrafters/atom (when signed in), so that's probably why trying to add it again fails.

Not sure why it doesn't show up on the list.

@cjwatson Do you know if there may be some issue with LP API, that getting snaps by URL prefix "https://github/snapcrafters" doesn't return all their snaps?

**Comment by bartaz** [comment]
@cjwatson Ah, good catch, we need to look into that. Snapcrafters have 68 repos now, so it may be the case that they were over this limit at some point.

Currently I happen to see `atom` back again:
<img width="1028" alt="screen shot 2018-12-04 at 11 29 55" src="https://user-images.githubusercontent.com/83575/49435950-24e79500-f7b8-11e8-8ccf-a6309be18ec7.png">

Will investigate further.

**Comment by cjwatson** [comment]
@bartaz It also depends on the other prefixes being requested.  Notice that we're using `findByURLPrefixes` with multiple prefixes, not `findByURLPrefix` with one, so the results for all of them come back in a single collection.

**Comment by bartaz** [comment]
Good point, thanks!

**Comment by diddledan** [comment]
This looks similar to my issue #1175

**Comment by bartaz** [comment]
Happens again: #1198

**Comment by popey** [comment]
Still a problem. This makes it very frustrating as I frequently need to rebuild applications, and not being able to get to the "build now" slows down my workflow as I have to manually futz with URLs or trigger a build via other means.

**Comment by popey** [comment]
As a test I just removed a repo from the snapcrafters list on build, and another one (which was previously missing) now appears. So it appears we're hitting some internal limit.

**Comment by popey** [comment]
Yay! Thank you @bartaz ! This has really improved my day!
