### ISSUE TITLE
[header] “Sign out” doesn’t do anything

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#305]
0\. Sign in to build.snapcraft.io if you aren’t already.
1\. Choose “Sign out”.
2\. Choose “Sign in”.

What happens: You see your list of repos, and can add more, remove them (once that’s implemented), register snap names, etc.

What should happen: You’re required to authenticate to GitHub again before you can see your repos, and to Ubuntu One before you can register a snap name.

Apparently Travis does something similar. I don’t think that makes it okay — especially when we’re demoing it on a public-facing machine.

---

Copied from Trello card: https://trello.com/c/pmqxkHhH/254-header-sign-out-doesn-t-do-anything
Labels: Bug

**Comment by pmahnke** [comment]
FROM TRELLO

Evan
@bartoszopka how can you switch GitHub accounts if we don't sign you out completely?
Mar 4 at 3:09 PM - Reply
Robin Winslow (robinwinslow)Robin Winslow moved this card from Copy to GitHub to BacklogMar 3 at 10:47 PM
Robin Winslow (robinwinslow)Robin Winslow moved this card from Backlog to Copy to GitHubMar 3 at 10:35 PM
Bartek Szopka (bartoszopka)
Bartek Szopka
Currently "Sign out" clears the user session on BSI side meaning it removes any access tokens and macaroons it has from GH, SSO and snap store.

This means that user will need to go through SSO again to register new name. If they are logged in again they may not need to enter their username and password again, but they should be shown SSO screen with their user data that will be passed to BSI.

When it comes to GitHub after signing out from BSI and signing in again BSI needs to ask GitHub for authorisation. If user is currently logged into GitHub and has already granted BSI access permissions before (they authorised the app to access their GH account) BSI will log in to their current GH account without any further confirmation screens.

So it's not that "Sign out" doesn't do anything - it does everything it should from BSI perspective - it clear all the access tokens it has from GH and SSO for current user session.

So for the straw-man proposal suggested: 1. is already being done
2. would in my opinion be very confusing and unexpected user experience. As a developer and user of GitHub I wouldn't know why signing out from BSI asks me to log out from GitHub.

While I understand the possible security concerns when demoing BSI on public machine and leaving user signed in to GitHub I don't think we should break the conventions of GitHub single sign on that developers and users of GitHub (who are our target audience) are already used to.
Mar 2 at 11:00 AM (edited) - Reply
Matthew Paul Thomas (matthewpaulthomas)
Matthew Paul Thomas
I guess this is too late to be an MWC isssue, but still applies to anyone who thinks “Sign out” will do something. Someone using b.s.i on their own secure machine probably won’t bother signing out in the first place.

@bartoszopka Thanks for the https://github.com/logout suggestion, that looks promising. Straw-man proposal: when you choose “Sign out”,

b.s.i tells Ubuntu One to revoke its access to your account, then
you’re redirected to github.com/logout.
Mar 2 at 10:07 AM - Reply - Add Link as Attachment
Bartek Szopka (bartoszopka)
Bartek Szopka
This may be hard, as it seems from GH OAuth API docs that once user authorises the app they will not see login screen when signing in to the app as long as they are logged into their GH account.

From: https://developer.github.com/v3/oauth/#parameters

"For users who have authorized scopes for the application, the user won't be shown the OAuth authorization page with the list of scopes. Instead, this step of the flow will automatically complete with the set of scopes the user has authorized for the application."
Also it doesn't seem like we can't force or request GH to log out current user. Our application is only granted a limited access to users data from GH (their repos, etc), but we can't log in or log out from GH on their behalf.

The only thing I found that maybe helpful is linking to http://github.com/logout

But it's a separate page on GH and it doesn't link back to BSI, so once user goes there they won't get back to BSI after logging out.
Also they would still need to log out from BSI first (to revoke access tokens BSI has in user session).
So I'm not sure where would be a good place for it in BSI UI. Redirecting to github.com/logout after user signs out doesn't seem good solution as it means users a forced out of BSI and are not redirected back, which is not expected.

In real use logging out from GH shouldn't be an issue - developers used to using GH login will expect it to work this way (as a single sign on).

For the sake of MWC demo this may be an issue, so either people demoing need to remember to open new private session for every new user or may point users to http://github.com/logout after the demo to reassure them they are logged out from GH.

**Comment by nottrobin** [comment]
I'm wondering if the solution might be to completely remove the "sign in" and "sign out" wording, because as long as you stay logged in to a GitHub account that BSI is authorised to use, they are kind of meaningless.

Is it possible to simply check for every visitor whether they are already authenticated with GitHub? Because  then we could just always display the account info in the top right. If we're worried about people being surprised that they're logged in already, we could update the branding of that top right account display to make it more obvious that it's your GitHub account that you're in fact signed in to.

Where the "sign out" button used to be, we could perhaps provide a link for them to manage their application permissions on GitHub, this might help to make it more clear to the user what's going on.

If they're not authenticated then we could either display a button saying "Authenticate with GitHub" or just display nothing up there (since there are ample buttons around on the homepage asking them to authenticate with GitHub already).

**Comment by matthewpaulthomas** [comment]
Proposal: “‘Sign out’ should open [GitHub’s sign-out page](https://github.com/logout) in a new window/tab, so you can choose whether you want to sign out from GitHub altogether. In the existing window/tab, it should sign out Snapcraft from Ubuntu SSO, and go to the front page.”

**Comment by evandandrea** [comment]
👍

**Comment by nottrobin** [comment]
I've never seen a site that had a button to sign out of the supporting SSO service. I think this pattern would be surprising to most people. I can imagine clicking it, thinking I'm signing out of BSI, not realising I've gone to GitHub and that it's just some sort of confirmation page, and then being surprised and annoyed that I'm signed out of GitHub.

**Comment by matthewpaulthomas** [comment]
I agree that taking people to GitHub’s sign-out page may lead to people signing out of GitHub when they don’t mean to, and that the consequence would be surprise and annoyance.

Unfortunately, the consequences of the opposite case — staying signed in when you don’t mean to — could be much worse. Once we implement private repos, a simple vulnerability would be that an attacker could browse them. But already, for public repos, they could follow the link for editing snapcraft.yaml, navigate to adding or editing another file instead, commit the change, and your snap is now malware. Your only defence would be that someone notices the unusual revision to your repo before you next promote a build to beta/candidate/stable. And even that defence would be gone once we let you promote a build with a button rather than giving you a terminal command (which requires you to be signed in to SSO at your terminal). The stakes for Snapcraft are higher than with a CI-only service like Travis.

So I think there are two reasonable choices: (A) “Sign out” invites you to sign out of GitHub, or (B) as you suggested, we don’t have “Sign in” + “Sign out” at all.

At the moment I don’t think (B) is practical, because it would leave you with no way to sign out b.s.i from Ubuntu One. (Even if people knew how to get to login.ubuntu.com, it’s no help: “you have not been automatically logged out of every website that uses this service”.) And as long as b.s.i is signed in to Ubuntu One, an attacker could rename snaps, and in future even give up old snap names.

To summarize: we need UI for you to sign b.s.i out of Ubuntu One, and as long as we have it, it would be dangerously misleading for it not to at least invite you to sign out of GitHub too.

**Comment by bartaz** [comment]
Maybe another way around this would be to have a separate 'signed out' page on BSI.

Currently we just redirect users back to landing page.

Maybe we can have a separate page (like build.snapcraft.io/signedout), so that, when user clicks 'Sign out' their session on BSI will be cleared and they will be redirected to this 'signed out' page, that would say something along "You successfully signed out form Snapcraft but if you are still signed in Ubuntu One and Github. To fully secure your data you may want to sign out from these services. [links to Ubuntu One sign out and to Github signout] or you may go back to Snapcraft landing page..."

**Comment by nottrobin** [comment]
> Once we implement private repos, a simple vulnerability would be that an attacker could browse them. But already, for public repos, they could follow the link for editing snapcraft.yaml, navigate to adding or editing another file instead, commit the change, and your snap is now malware

I didn't understand this point. If they are signed in to GitHub then a malicious attacker can simply go over to github.com and make those same edits. We are not providing an attack path that is not already there.

> At the moment I don’t think (B) is practical, because it would leave you with no way to sign out b.s.i from Ubuntu One. (Even if people knew how to get to login.ubuntu.com, it’s no help: “you have not been automatically logged out of every website that uses this service”.) And as long as b.s.i is signed in to Ubuntu One, an attacker could rename snaps, and in future even give up old snap names.

Ah, so perhaps the real problem is Ubuntu One, and the reason we really need a "sign out" button is because we need you to be able to sign out of Ubuntu One. In which case the problem for me is really that the app doesn't provide any clear indication of what your logged-in state to Ubuntu One is. I think this is really where the thinking needs to happen - how do we clearly indicate your state regarding Ubuntu One, and let you control it.

I still think that the "sign out" button makes no sense with regard to GitHub, and since GitHub is the *primary* authentication method, it makes no sense.

It is confusing that you can be authenticated against two services, or one, or neither. Maybe what should really happen is that the primary and only authentication source should be Ubuntu One, and then you would authorize that account to use GitHub in the backend - the front-end app would retrieve all information from GitHub through the back-end, so we don't need front-end authentication to GitHub at all. Thoughts?

**Comment by bartaz** [comment]
> Maybe what should really happen is that the primary and only authentication source should be Ubuntu One

As far as I remember from the beginning of the project one of the main requirements was to have GH as primary authentication and only sign in to Ubuntu One SSO when it is needed (for name registration, etc) and show Ubuntu One as little as possible.

The idea was, that developers likely already have GH account they can use, but likely don't have Ubuntu One account to sign in.

But maybe that needs to be reconsidered, especially as it seems that using GH organisations also may require some connection between Ubuntu One and GH accounts.

**Comment by evandandrea** [comment]
>Maybe what should really happen is that the primary and only authentication source should be Ubuntu One, and then you would authorize that account to use GitHub in the backend - the front-end app would retrieve all information from GitHub through the back-end, so we don't need front-end authentication to GitHub at all.

A big motivator for this website is to start the millions of active GitHub users from a point of prior understanding, a comfortable place. That is their GitHub identity.

**Comment by matthewpaulthomas** [comment]
> If they are signed in to GitHub then a malicious attacker can simply go over to github.com and make those same edits. We are not providing an attack path that is not already there.

Good point. I guess my concern was that people who had authorized to GitHub would not realize that they were signed in to GitHub generally. But, eh, these are software developers.

So, how about this?

![A menu in the header, with your icon and GitHub user name as its title, containing items “Settings”, “GitHub profile”, “Sign out of Snapcraft”, and “Sign out of Snapcraft+GitHub”.](https://cloud.githubusercontent.com/assets/19801137/24364989/5d018cd0-130c-11e7-808b-bcc49bbe31a1.png)

“Sign out of Snapcraft” would sign out build.snapcraft.io from SSO and take you to the front page. “Sign out of Snapcraft+GitHub” would do the same, except taking you to GitHub’s signout page.

**Comment by nottrobin** [comment]
I like that better, but I still think it's very unclear what "Sign out of Snapcraft" means. I think we need to either explain to them about the existence of SSO, or hide it from them completely. This fuzzy middle way where being "signed in" mostly means GitHub but sometimes is a secret reference to SSO is very confusing.

**Comment by matthewpaulthomas** [comment]
What it means is “sign out of the ability to register/change/reallocate snap names”. Now, maybe that isn’t useful, separate from signing out of GitHub too. If it isn’t, the menu could just have the “Sign out of Snapcraft+GitHub” item.

**Comment by nottrobin** [comment]
> What it means is “sign out of the ability to register/change/reallocate snap names”. Now, maybe that isn’t useful, separate from signing out of GitHub too.

My understanding is that it isn't useful - being signed in to GitHub is really the whole deal - but @bartaz or @cjwatson tell me if you disagree.

Otherwise the design looks good to me, the "Sign out of Snaocraft + GitHub" item is a good one. Although maybe just "Sign out of GitHub" is less clumsy, and then simply by its existence at the only option it's implied that this is how you sign out of Snapcraft. Thoughts? I'm happy either way.

**Comment by nottrobin** [comment]
Also we decided that there shouldn't be a "settings" page on build.snapcraft.io itself. So unless "settings" refers to a GitHub settings page, I don't think we need that item. If it does refer to a GitHub settings page, I think it should be more explicit.

So maybe we just need "GitHub profile" and "Sign out of GitHub".

**Comment by matthewpaulthomas** [comment]
Seven months later, we now understand better that BSI will be integrated with the rest of the publisher service. We should still encourage people to start just by authenticating to GitHub, since that’s the easiest thing to do, if that’s where their code is — but it might not be. Being signed in to GitHub is no longer “the whole deal”. This means you can be in any of four states: signed in to the Snap Store or not × authenticated to GitHub or not.

So, here’s a proposal for how the menu should look in each of those four states.
![profile menu variations](https://user-images.githubusercontent.com/19801137/33566376-b0b40fe8-d917-11e7-9429-256fcac6b6bd.png)

The title would show your Snap Store full name if you were signed in; otherwise your GitHub profile name if you were authed to GitHub; otherwise “Sign in”.

When signed in to neither, your primary method of authing to GitHub would be by a button on the front page (or [in the “Get Started” flow](https://docs.google.com/document/d/1bdZnkT7UjLp9r8q2xoujYRGR--cz_fCgbyDNQEWXXfw/edit#heading=h.7i006o4j4ww3)). The “Show my GitHub snaps” item would be mainly for returning users who don’t have a Snap Store account yet.

While there are no current “Settings” when authed to GitHub, there is currently “Account details” when signed in to dashboard.snapcraft.io. Here, that would become “Snap Store account” to distinguish it from your GitHub account.

If you’re only authed to GitHub, the last item would be “Sign out of GitHub…”. If you’re signed in to the Snap Store as well, we’d avoid having two “Sign out” menu items by offering the function in the notification instead.
![sign-out notification](https://user-images.githubusercontent.com/19801137/33567060-d9889054-d919-11e7-936a-49ab1684c7d1.png)

**Comment by matthewpaulthomas** [comment]
From review by @carlaberkers:
- [ ] Signed in to Snap Store but not authed to GitHub: add “Show my GitHub snaps” here too
- [ ] clarify that “Sign out of GitHub…” also revokes BSI’s GitHub auth
- [ ] If a baddie takes your GitHub session and makes a linked store account, how would you know?

**Comment by nottrobin** [comment]
@matthewpaulthomas If a baddie gets hold of your GitHub session, you're in trouble. There are many attack vectors from that point. I don't think them triggering builds automatically from your webhooks is anywhere near the worst of your concerns.

I agree that we should try to design our app to be secure, but if your GitHub account is compromised, I think we have to accept we can't always protect you.

**Comment by nottrobin** [comment]
Thanks for bringing this back up @matthewpaulthomas.

I think maybe I'm not quite aware of all the ways in which the state of things has changed:

> Being signed in to GitHub is no longer “the whole deal”.

Is this true? Is it definitely in the plan to start supporting building from other sources? And if so, what's the timeline for that?

Under the current flow, my understanding is that you *have* to sign in to GitHub first, and then later you might be asked to sign in to SSO. If that's the case, there are only 3 possible states: 1. Not signed in anywhere, 2. Signed into GitHub and not SSO, 3. Signed into both. While this is still the case, we should design for that flow and ignore the "signed in to SSO and not GitHub" option. That could avoid the need for "Show my GitHub snaps" (which I don't much like - I'm not quite sure what "my GitHub snaps" are, it makes it looks kinda like GitHub is somehow centrally involved in either owning or building snaps, which it's not).

When this changes so that GitHub is *not* the mandatory first step, I would suggest we take the opportunity to radically simplify the login by centralising it purely around SSO: You would sign in to SSO first, and then GitHub would be in an "authorised apps" section of your account settings (similar to https://github.com/settings/applications).

**Comment by matthewpaulthomas** [comment]
> Is it definitely in the plan to start supporting building from other sources? And if so, what's the timeline for that?

The store team would know better, but I think it was sometime in 2015.

> Under the current flow, my understanding is that you have to sign in to GitHub first

That is true only on build.snapcraft.io. Though this issue is filed under BSI, I’m aiming for the design to continue working when, as I said, BSI will be integrated with the rest of the publisher service — so you might be building from GitHub, or you might not.

> I would suggest we take the opportunity to radically simplify the login by centralising it purely around SSO: You would sign in to SSO first

That would make login simpler, but it would make _signup_ much more complicated and less palatable: registering an Ubuntu One account, including confirming your e-mail address, instead of just clicking a GitHub auth button. Compare [App Center](https://appcenter.ms/login): authing with GitHub is the first choice, but you can register a dedicated account instead.

**Comment by nottrobin** [comment]
> That is true only on build.snapcraft.io. Though this issue is filed under BSI, I’m aiming for the design to continue working when, as I said, BSI will be integrated with the rest of the publisher service — so you might be building from GitHub, or you might not.

@matthewpaulthomas Yes that's a good point, we need to think about the eventual unified experience. I actually think this strengthens my point.

My understanding is that it's always been the plan to directly tie sign in for the wider snap store to an SSO account as the primary sign-in method. I really can't imagine anything else being acceptable. Users of the snap store should not be at all surprised at having to create an account within our system if they want to significantly interact with said store. And signing in to GitHub will make absolutely no sense for most of those users.

So the only question remaining is:

*Do we want to update build.snapcraft.io to be unified behind a SSO account first-and-foremost at this point? Or should we only do it at the point we migrate it into snapcraft.io?*

My preference is actually for the latter. I think it will be very difficult to update the existing build.snapcraft.io experience, and so we may as well defer it until we're overhauling the system anyway. Coupled with the fact we don't yet know the timeline for that integration, or exactly what shape it will take.

**Comment by matthewpaulthomas** [comment]
> My understanding is that it's always been the plan to directly tie sign in for the wider snap store to an SSO account as the primary sign-in method. I really can't imagine anything else being acceptable.

I expect @evandandrea would disagree with that now just as he did when you suggested it in March. As I understand it:
1. To auto-build a GitHub repo, you need to auth to GitHub.
2. To release a snap, you need a Store account; a GitHub account won’t do.
3. Therefore, to release snaps auto-built from GitHub, you need to auth to GitHub _and_ sign up to the Store.
4. However, you can (as demonstrated by BSI currently) get as far as setting up set up auto-builds without needing a Store account. And if your team role doesn’t involve releases or editorial, you won’t ever need a Store account.
5. Therefore, we achieve a lower dropoff rate by requiring Store signup only if+when it’s needed, rather than up-front.

If any of that changed, I think it would most likely be (2). But again, this is not so different from App Center: you can sign up there using GitHub, but if you’re going to release your app to the App Store or Google Play, you still need an Apple or Google developer account as well.

> Coupled with the fact we don't yet know the timeline for that integration, or exactly what shape it will take.

@Lukewh has started implementing the publisher-facing snap pages. [My design for the publisher-facing snap Build page](https://github.com/CanonicalLtd/snapcraft-design/issues/56#issuecomment-325942727) is intended to obsolete BSI’s repo page. Given that we have adequate, functional pages on dashboard.snapcraft.io and build.snapcraft.io, which we know we want to integrate, designing and implementing a page that replaced only one of them probably wouldn’t be a good use of time.

**Comment by nottrobin** [comment]
As long as build.snapcraft.io is purely a tool for building snaps from GitHub repositories, I totally agree with you and @evandandrea that the smoothest onboarding experience is to ask people to sign in to GitHub. I haven't heard @evandandrea express an opinion about the sign-in experience for a unified snap store, but I'd of course be interested to hear it.

In the context of a unified snap store, which is currently planned to live at https://snapcraft.io, automatically building snaps is feature which a relatively small proportion of the users will use. It makes absolutely no sense to massively complicate the sign-in experience purely to accommodate this relatively uncommon flow. As I say, the snap store, like dashboard.snapcraft.io, was always intended to back onto the SSO account system and nothing else. This is just obvious.

If we want to keep build.snapcraft.io as a GitHub-centric experience, the only option is *not* to integrate it into snapcraft.io.

**Comment by matthewpaulthomas** [comment]
Ok, so this has turned out to be dependent on the larger discussion about developer-centric vs. end-user-centric pages. Here’s my understanding, on a higher level than what I wrote above:
1. A Web site that knows what snaps you have installed per-device (like play.google.com does), and that has the ability to instruct snapd to install/remove software (like Landscape does), would require `snapd` changes that (a) aren’t on the roadmap and (b) would run counter to this year’s change of no longer requiring U1 sign-in to install free snaps.
2. Therefore, installing and removing snaps will continue being handled by Gnome Software and similar local apps (which also have the major benefit of offering non-snap software as well). Discover’s “Install” buttons will continue handing off to your local storefront.
3. Therefore, Discover is not a storefront, but a snap directory, existing for search engine presence and graceful linking. (Both important things!) We’ll require sign-in for payments, reviewing, and flagging, but  pages for those functions will be embedded by local storefronts (as they were by Ubuntu Software Center), with little or no on-page navigation.
4. Therefore, it would be misleadingly pointless to have sign-in as part of global navigation on Discover pages. (If you clicked a “Report as inappropriate” button, _then_ we might prompt you to sign in.)
5. Therefore, sign-in as part of global navigation is appropriate only on developer-centric pages.
6. Even if any of the previous points are incorrect, it’s not certain that unprompted end-user sign-in and developer sign-in could sensibly end up at the same place ([snapcraft.io#183](https://github.com/canonical-websites/snapcraft.io/issues/183)), so the developer sign-in UI might be different anyway.
7. Many, if not most, snap developers will have their code on GitHub.
8. Therefore, auto-builds will be useful to many, if not most, people who use this sign-in UI. (The main reasons not to use auto-builds are if your code is proprietary, or pushed from a CI system instead.)
9. If you will be auto-building from GitHub, getting started by authing GitHub is much easier than by registering an Ubuntu One account (as outlined in my previous comment).
10. Therefore, it’s appropriate to present GitHub auth status in this sign-in UI.

> As I say, the snap store, like dashboard.snapcraft.io, was always intended to back onto the SSO account system and nothing else. This is just obvious.

Not at all — a year ago, it nearly turned out differently.

> Not to mention that it would be super odd for us as a company to use GitHub as the primary authentication method for Canonical's main store when we have our own login system.

Once again I have to point to Microsoft’s App Center: Microsoft has had their own single sign-on system for 18 years. Nevertheless, “Continue with Microsoft” is option 2. Option 1 is “Continue with GitHub”, because that’s where the users are.

Anyway, here’s my revised design assuming all that. _If_ Discover and the developer service were treated as a single site, with the same navigation and sign-in, it would indeed “massively complicate the sign-in experience purely to accommodate this relatively uncommon flow”. So at the least, this work may help illustrate the tradeoffs involved in having them combined vs. distinct.

![profile menu variations](https://user-images.githubusercontent.com/19801137/33991905-7ab9030e-e0c8-11e7-97d9-468f0c0e4b53.png)

> If a baddie gets hold of your GitHub session, you're in trouble. There are many attack vectors from that point. I don't think them triggering builds automatically from your webhooks is anywhere near the worst of your concerns.

Good point. For that reason I’ve left the “Sign out of GitHub…” wording as-is. Signing out of GitHub is the important thing; that you’ll need to sign in again to see your unregistered auto-builds is just one of the consequences.

**Comment by nottrobin** [comment]
Just a couple of quick points:

> We’ll require sign-in for payments, reviewing, and flagging, but pages for those functions will be embedded by local storefronts (as they were by Ubuntu Software Center), with little or no on-page navigation.

Sorry, you're saying here that payments will be only done through a local app, and not through the website at all? This wasn't the only thing either - there are a number of things on the roadmap that require end-user login - @carlaberkers could you remind us what they are?

> Many, if not most, snap developers will have their code on GitHub.
> Therefore, auto-builds will be useful to many, if not most, people who use this sign-in UI

The difference between "many" and "most" is absolutely central here. I think it is possible that the code behind most snap code is on GitHub, but much of it will be in private repos. But the main bit I disagree with is this assumption that people with code on GitHub will want their snaps to auto-build - especially if it can't push to stable. I don't even use build.snapcraft.io for my snaps.

I suspect that serious snaps will always have their own deployment pipeline and therefore definitely won't use our auto-build system.

**Comment by evandandrea** [comment]
>>Many, if not most, snap developers will have their code on GitHub.
Therefore, auto-builds will be useful to many, if not most, people who use this sign-in UI

>The difference between "many" and "most" is absolutely central here. I think it is possible that the code behind most snaps is on GitHub, but much of it will be in private repos. But the main bit I disagree with is this assumption that people with code on GitHub will want their snaps to auto-build - especially if it can't push to stable. I don't even use build.snapcraft.io for my snaps.

Sorry for arriving late to this.

1. There are over [67 million software repositories on GitHub](https://octoverse.github.com/). I know of no other source that even comes close.
2. We want to maintain the smoothest possible onramp for these most common developers. This work to unify the experience should not force them to create an SSO account prior to becoming sufficiently invested. The steps should start small and reward quickly, but both investment and return can grow as the individual progresses and develops trust.
3. Regardless of whether you personally chose to auto-build your GitHub repos or not, it is something we absolutely want to encourage other developers to do.

>My understanding is that it's always been the plan to directly tie sign in for the wider snap store to an SSO account as the primary sign-in method. I really can't imagine anything else being acceptable.

It was my understanding coming out of Cape Town that developers signing in via other providers (as @matthewpaulthomas [illustrated](https://appcenter.ms/login)) was on the roadmap. @noise would know more.

**Comment by nottrobin** [comment]
> It was my understanding coming out of New York that developers signing in via other providers (as @matthewpaulthomas illustrated) was on the roadmap. @noise would know more.

That's very interesting - I love the idea of login.ubuntu.com, or whatever our account system of the future is, allowing you to create an account from an existing OAuth provider to smooth the account creation process. This is what Microsoft do.

This is very different from authenticating you with GitHub and *not creating you an account on our system*, which is what we currently do as a first step on build.snapcraft.io.

**Comment by matthewpaulthomas** [comment]
> Sorry, you're saying here that payments will be only done through a local app, and not through the website at all?

I mean that some Web server will serve pages that provide UI for payments, that those pages will be embedded inside whichever local app you use to install software, and that for that reason, those pages should not have headers at all. All of this demonstrated five years ago by Ubuntu Software Center and pay.ubuntu.com.

> there are a number of things on the roadmap that require end-user login

Enterprise licensing etc for snaps may mean there is _also_ a need for payment pages that are accessible  from Discover (which would probably share most of their code with the app-embedded ones). Whether that deserves sign-in UI in the header depends, I think, on what proportion of visitors fall into that category.

**Comment by carlaberkers** [comment]
I discussed URLs and authentication with Mark before the Christmas break, main points were:

1) Authenticating with Github is not the same as logging in 
2) We all work for a company that has developed and maintained an identity provider (SSO), so we should be using what we already have. If we feel the SSO journey is too long we should improve it, rather than turning to other solutions.

So the question is what this means for this bug, as in the future, it means we should build on the new infrastructure using SSO. 

@nottrobin I imagine it would be significant extra work if we were to change this on the current build.snapcraft pages, is that correct?

**Comment by bartaz** [comment]
@carlaberkers 

> I imagine it would be significant extra work if we were to change this on the current build.snapcraft pages, is that correct?

Yes. Not only development work, but also UX/design. BSI was built on assumption that users authenticate via GitHub to have easy and quick access to their repositories. Most (if not all) user journeys in BSI are built around that assumption at this time. If we want users to sign in to SSO first this is a significant change.

A possibly quicker 'workaround' may be to keep current flow/journeys more or less as they are, but change the wording of GH authentication and possibly placement of it (out of the header?) so it doesn't feel like 'signing in' to BSI.

**Comment by nottrobin** [comment]
@carlaberkers yes it's significant work, as much from a UX perspective as anything else.

The **current flow** is more-or-less:

1. Authenticate with GitHub
2. Select repository to build
3. Sign in to SSO
4. Continue with build

The **quickest SSO-based flow** to implement would be:

1. Sign in with SSO (creating an account if you don't have one)
2. Authenticate with GitHub to link your GitHub account to your SSO account
3. Select repository to build

This would require UI changes to:

1. Make any "authenticate" and "log in" buttons make it clear you'll be sent to the separate login.ubuntu.com service to either create an account or sign into one
2. Provide a new page to explain that the user now needs to authorising their SSO account to use their GitHub account
3. Remove the references to "sign in" that currently happen at build-time

**The *ideal* SSO-based flow** would look more like [Microsoft's implementation](https://appcenter.ms/login) - but it would require changes to the SSO service to support GitHub as an identity provider:

1. "Authenticate with GitHub", go to GitHub, authorise
2a. If you previously had an SSO account, you're now logged into SSO; otherwise
2b. You're sent to login.ubuntu.com to create an account which will then be linked to your GitHub account
3. Select repository to build

This would mean that by being logged in to GitHub you're also logged in to SSO, but would require significant work in the SSO service to support this.

**Comment by nottrobin** [comment]
We discussed this briefly during the URLs meeting yesterday. As discussed then, here is an elaboration of what I see as the ideal login flow for snapcraft.io - specifically requested by @carlaberkers and @Lukewh:

We need to at least have the ability for a login.ubuntu.com account to be linked to a GitHub account (and maybe other places e.g. GitLab down the line), which means login.ubuntu.com needs extending to store GitHub identities.

Since we're doing this, I suggest we go all the way to supporting OAuth providers as login identities for login.ubuntu.com - this would make it much easier for people with GitHub (or Twitter, or Facebook, or Google) accounts to create and stay signed in to a login.ubuntu.com account. This should simply follow a common standard pattern for OAuth sign-in (@pmahnke also helped me simplify the flow here).

This would simplify the account creation process for normal users - it would add 1 extra click (to "Authorize" login.ubuntu.com to see your identity provider), but it would mean you don't need to fill in a single form field (and you don't need to create a new password):

![sketch - generic login](https://user-images.githubusercontent.com/519935/34558104-94e03bc2-f134-11e7-995a-60bd506f14b6.jpeg)

It also gives us the ability to hugely simplify the flow for the `/build` page to get to the point where you can see a list of your GitHub repositories - you just need the one click to authorize your GitHub account, and the login.ubuntu.com would be automatically created:

![sketch - link github for building snaps](https://user-images.githubusercontent.com/519935/34558171-d71a7cc8-f134-11e7-9a82-d81ab8dd4793.jpeg)

Sorry if it's all a bit messy. I can talk anyone through the diagrams who's curious.

**Comment by Lukewh** [comment]
Thanks for the diagrams @nottrobin, they help clarify.

I might be missing this from the diagram but what happens if I authorize with GitHub using [email 1]:
- GitHub is happy
- SSO creates a new account based on [email 1]
- I've created and pushed a snap via `snapcraft` using my [email 2] SSO account

Is there a way to link the two SSO accounts? I wouldn't want to log out from SSO to log in with GitHub to go between lists of snaps.

What would happen if you update your email address to [email 3] on GitHub then authenticate again from a different machine, would another SSO account be created? I'm semi-assuming SSO would store the account id from GitHub rather than *just* the email address, but I still think it could add complexity when linking by email addresses?

All of this might be trivial, but I'm still not convinced this is simpler than forcing SSO registration then allowing you to link GitHub, GitLab, BitBucket etc. No magic hidden accounts need creating in the background, in GitHub you'd just have the 'USSO app' with permissions.

**Comment by nottrobin** [comment]
@Lukewh Yes that difficulty did occur to me - @pmahnke and I discussed it. Although even with basic account systems people often end up creating multiple accounts when they forget which email they used previously etc.

I think we can try to mitigate it as far as possible by matching *all* the emails provided with GitHub (I think they can sometimes provide multiple?) with *all* the emails provided by GitHub. But ultimately we can't ever completely avoid people accidentally creating multiple accounts with any system. If people do get their knickers in a twist I'm sure they can contact us to help sort it out for them.

In any case, this is definitely an edge-case, and I think (and I believe @pmahnke at least agrees with me) that the overall benefits of allowing people to use their existing identities to authenticate outweigh this downsides of this complex edge-case.

**Comment by nottrobin** [comment]
> I'm still not convinced this is simpler than forcing SSO registration

The really important point is that we are still forcing SSO registration, we're just handling most of it automatically in the background.

The system I'm suggesting is *definitely* more complex to *implement*, but I think its simpler for the user. I would be sympathetic to the suggestion that a auth system that doesn't use third party identities at all is simpler, except that we already need to handle a third party identity for GitHub. Given that constraint, I don't really understand why we wouldn't follow the standard existing models for using third party identities for logging in.

**Comment by matthewpaulthomas** [comment]
I think it would be great if you could use just a GitHub account to publish snaps. I understand that this might be a problem because of what might happen if, for example, your software becomes installed on thousands of devices and then GitHub revokes your account.

I also think it would be great if, instead, authing to GitHub on our build service auto-created an SSO account for you.

But I don’t think either of those possibilities actually alter the UI I’ve proposed above, so I think they’d best be discussed elsewhere. If you could use a GitHub account to publish snaps, that would alter the destination of the “Sign in to Snap Store” link. But there would still be a need to sign out of the store, and separately to sign out of GitHub.

**Comment by nottrobin** [comment]
@carlaberkers, @pmahnke and I discussed this.

We've decided that the rough shape that I suggested for the login flow is best, as it provides the most unobtrusive journey for authenticating with GitHub while still centralising everything around an login.ubuntu.com (SSO) account - which meets Mark's requirement.

However, changes would have to be made to login.ubuntu.com to accommodate associating a GitHub identity with an SSO account - and currently we don't know how difficult it will be to make improvements to login.ubuntu.com, with the assumption that it might be quite difficult.

Therefore we need to work towards my login flow for snapcraft.io in stages - as we don't need the ability to associate GitHub identities until we integrate the functionality from build.snapcraft.io into the site. So, roughly, these stages would be:

1. Basic login: A simple login system based purely around login.ubuntu.com, as it currently exists (basically what you see if you visit https://snapcraft.io/account)
2. Linking with GitHub identites: Add the ability to link a GitHub account with a login.ubuntu.com account, and manage that association through login.ubuntu.com
3. Authentication with GitHub: Add the ability to login and create accounts for login.ubuntu.com by authentication with GitHub, to simplify the user experience
4. (Hypothetical) More authentication providers: Add other auth providers - like Twitter, Google, Facebook etc.

We can proceed with "Basic login" immediately. But "Linking with GitHub identities" onwards are blocked on working out how we get login.ubuntu.com developed - and therefore migrating build.snapcraft.io to snapcraft.io is also blocked on that.

This significantly impacts @matthewpaulthomas's designs above because there will no longer be any need to display your "Authenticated to GitHub" state. You will only ever be logged in in one place -
 login.ubuntu.com - and any linked identities will be managed through login.ubuntu.com. So we can simply display a basic "clock to log in" / "logged in as X" state.

We have a meeting next week to discuss the snapcraft.io header, which will presumably include some discussion of what the log in button looks like. At that point we'll track how to progress the work for snapcraft.io's login system, which should then be tracked elsewhere.

As regards this issue, given that it's now entirely clear that build.snapcraft.io will ultimately move to snapcraft.io, we won't be revisiting build.snapcraft.io's login system. So I'm going to close this issue.
