### ISSUE TITLE
GitHub authentication page - description, app name and logo need updating [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#322]
This is what the authentication page currently looks like:

![auth page](https://assets.ubuntu.com/v1/0f11bc28-authentication.png)

Update the authentication page as per the spec.

**Comment by evandandrea** [comment]
Spec: https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q68bf3rlr1z3

**Comment by evandandrea** [comment]
Logo: ![snapcraft_s_800x800_hex](https://cloud.githubusercontent.com/assets/1523179/25277330/140a47e0-2696-11e7-8b13-10a94bda535c.png)

**Comment by matthewpaulthomas** [comment]
@cjwatson, as above, right now we’re asking for just one permission, “Repository webhooks and services”. Would this be an accurate description of why?
> We use webhooks so that your code builds automatically after each commit. We also respond when your configuration file, snapcraft.yaml, has been added or changed.

**Comment by cjwatson** [comment]
@matthewpaulthomas That's accurate, although it took me several readings to understand why the second sentence wasn't covered by the first one (it's because we notice name changes).  Perhaps "We also detect the name of your snap from your configuration file, snapcraft.yaml, when it is added or changed"?  But consider just leaving out the second sentence altogether; it's a minor detail and I don't think it adds very much.

Also, on staging we in fact ask for another permission, "Organizations and teams" → "Read-only access", in order to be able to see repositories of organizations you belong to.

**Comment by matthewpaulthomas** [comment]
@cjwatson Thanks. So, second draft:
> We use webhooks so that your code builds automatically after each commit. And we look at your organizations so that we can show you their repos.

**Comment by cjwatson** [comment]
Looks fine to me.

(I don't object to conjunctions at the start of sentences on principle, but I'm not sure it's called for here.  Perhaps just "We" at the start of the second sentence?)

**Comment by matthewpaulthomas** [comment]
Okay, [spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.q68bf3rlr1z3) with that text minus the “And”.

**Comment by matthewpaulthomas** [comment]
This seems to have been closed by mistake. The only item that has been updated is the logo, which is already covered by #722, which hasn’t been closed. Meanwhile, the app name, vendor, and description text all have not been updated, either on production or staging.

**Comment by bartaz** [comment]
I believe @earnubs was closing it because he was updating it.

By 'vendor' you mean current "... by `@build-snapcraft-io`"?

<img width="803" alt="screen shot 2017-05-11 at 13 24 33" src="https://cloud.githubusercontent.com/assets/83575/25946901/58877fde-364d-11e7-8ab2-ecf937551d96.png">

I don't know how much we can change that. It's a GH user name of user who registers given up. I don't believe we have any 'Canonical' user, and application cannot be registered by organization I believe.

**Comment by earnubs** [comment]
#722 is about the favicon, this isn't about the favicon :)

**Comment by earnubs** [comment]
All the requested changes have been made as far as I can see:
https://github.com/build-snapcraft-io
https://github.com/build-staging-snapcraft-io

...but if I've have something wrong, happy to fix it.

**Comment by bartaz** [comment]
@earnubs Changes were meant to be done to BSI app authorization, not GH accounts.

So text that shows up when user first authenticates the app needs to be updated.
This should be available via Settings of users that created the app (https://github.com/settings/developers)

**Comment by earnubs** [comment]
@matthewpaulthomas Updated both accounts, can you check and mark this closed if you're happy?

**Comment by matthewpaulthomas** [comment]
✔ App name
✔ Vendor name (spec updated)
✔ Logo
✘ Description text

Apparently GitHub has redesigned this page. I’m not sure whether the new design has discarded description text, or whether our text has just been entered in the wrong place.

![322-github-auth](https://cloud.githubusercontent.com/assets/19801137/26496149/3e4e5930-421e-11e7-9d97-4ab1b8489eac.png)

**Comment by bartaz** [comment]
Application settings seem to be filled just fine.
So it may be that GH stopped showing description on authorization screen.

<img width="553" alt="screen shot 2017-05-26 at 15 36 12" src="https://cloud.githubusercontent.com/assets/83575/26496783/23231ab4-4229-11e7-9f1f-98b99fc29c76.png">

**Comment by bartaz** [comment]
From GH support:

"Thanks for reaching out about this, Bartek. Yeah, that page was redesigned recently and it's definitely possible that the description is no longer shown as a result of that. I'll open an internal issue to double-check that this was intentional and also pass your feedback along to the team so that they know you'd like it to be shown. We'll followup as soon as there's any news, but I can't promise an ETA."

**Comment by bartaz** [comment]
From GH support:

"Just wanted to followup here after discussing this with the team. This was an intentional change -- both the description and the homepage URL were removed from the OAuth authorization page in an effort to reduce the risk of phishing on that page. The team is considering ways to surface that information again to users, but I can't promise when that might happen (and it's possible it won't happen in the near future). For now, I'd recommend surfacing the information you wanted to show to your users in a different way (e.g. by putting it on the page where you link to the OAuth flow)."

**Comment by nottrobin** [comment]
@bartaz does this mean this is done and can be closed?

**Comment by bartaz** [comment]
This means that description is not (and likely won't in close future) be visible on authorization page and we can't do much about it.

So I believe this issue may be closed and if we want to explain why we ask for particular rights we need to do ourselves inside of BSI.
