### ISSUE TITLE
Cross browser testing

### ISSUE THREAD

**Issue by ghost** [canonical-websites/build.snapcraft.io#448]

**Comment by earnubs** [comment]
Please define the list of supported browsers.

**Comment by magdalena-mirowicz** [comment]
@jamiedawsonyoung Tasks for you within it:

- Share asap list of supported browsers
- Organise testing session early next week. I'm happy to help if needbe

**Comment by jamiedawsonyoung** [comment]
@earnubs So this is the list of browsers that we test Vanilla patterns on, it would seem to make sense to start with these ones: 

- Google Chrome (latest stable)
- Mozilla Firefox (latest stable)
- Apple Safari (latest)
- Google Chrome for Android and iOS (latest stable)
- Microsoft IE 9+
- Microsoft Edge
- Apple Safari for iOS (latest)
- Opera (latest stable)
- Opera Mini (latest stable)

Unless you have any objections to any of them. 

We're prioritising the desktop experience for now because as far as I'm aware there's been little or no work on making the site responsive. Will be good to see how it performs on mobile browsers all the same.

**Comment by jamiedawsonyoung** [comment]
Also worthwhile adding what we'll test: 
Landing page:
- Visual bugs
- Links / buttons
- Sign in and out of GitHub

Dashboard
- Adding a repo 
- Configuring a repo
- Registering a name
- Viewing a build page
- Viewing a build details page
- Sign in and out of SSO
- Removing a repo from the list
- All links 

@matthewpaulthomas @magdalena-mirowicz  Can you think of anything else?

**Comment by jamiedawsonyoung** [comment]
I'm also going to test on only a small laptop size viewport (1280x800) for now.

**Comment by jamiedawsonyoung** [comment]
I've also made a [spreadsheet](https://docs.google.com/a/canonical.com/spreadsheets/d/10CXta2ePQRwkV6S7RN3ZxHjMI0mAyH9mfBiZQ7l-MX8/edit?usp=sharing) (oh help me god) for this.

**Comment by jamiedawsonyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cross browser testing #448](https://trello.com/c/hZzjEeIs/602-cross-browser-testing-448)

**Comment by earnubs** [comment]
Opera Mini might be a problem?

**Comment by evandandrea** [comment]
@popey is doing the Windows testing, I'm doing Mac.

**Comment by magdalena-mirowicz** [comment]
@evandandrea hey Evan just checking if you have a capacity early next week to do browser testing again?

**Comment by evandandrea** [comment]
Yup!

**Comment by carlaberkers** [comment]
GA was ages ago, think we forgot to close this bug
