### ISSUE TITLE
build.snapcraft.io should honour target-architectures when that lands in snapcraft

### ISSUE THREAD

**Issue by popey** [canonical-websites/build.snapcraft.io#556]
My yaml has:-
architectures: [amd64]
Because I know it fails to build on armhf, and I'm only testing on amd64, so pointless wasting cpu cycles on 40 min armhf builds. 
I realise build is explicitly limited to amd64 and armhf (and currently not i386), but it would be nice if I could force _not_ to build on armhf for example.

**Comment by flexiondotorg** [comment]
I am running into the same issue for a different use case. A snapcraft.yaml that ingests a tarball from CI and said tarball is amd64 only, but there are now builds in the store for armhf and amd64.

**Comment by evandandrea** [comment]
Also encountered [here](https://forum.snapcraft.io/t/how-to-trigger-builds-on-launchpad-upon-upstream-repository-update/643)

**Comment by cjwatson** [comment]
Sadly this isn't what the `architectures` field means in `snapcraft.yaml`.  Setting that field declares that you're building a single multi-architecture snap that works on that set of architectures: you get a `*_multi.snap` with that set of architectures in its `meta/snap.yaml`.  That's not at all what's wanted here.

I agree that we should have the feature of being able to declare what architectures you want the snap to be built for, but it can't be done with the existing `architectures` field.

**Comment by evandandrea** [comment]
Sorry for the confusion. I just spoke with Sergio and Snapcraft will gain an option for specifying what architectures a snap should be built on:
https://lists.ubuntu.com/archives/snappy-app-devel/2016-April/000654.html

**Comment by evandandrea** [comment]
Another reason for letting the developer limit the target architectures in the snapcraft.yaml, [anbox's build badge shows as "failing"](https://build.snapcraft.io/user/anbox/anbox) because it's (seemingly) not intended to work on ARM.

**Comment by evandandrea** [comment]
@sergiusens, can you estimate when this might land in snapcraft?

**Comment by sergiusens** [comment]
Let me bring the mailing list post into the forums.

**Comment by elopio** [comment]
For reference, this is the discussion in the forum:
https://forum.snapcraft.io/t/snapcraft-build-on-hint-for-builders/939

**Comment by matthewpaulthomas** [comment]
Looks like the current dependency is [snapcraft#1681](https://github.com/snapcore/snapcraft/issues/1681).

**Comment by jdxcode** [comment]
because https://github.com/snapcore/snapcraft/issues/1681 is merged does that mean this is available now?

**Comment by sergiusens** [comment]
It is on snapcraft's side, but build.snapcraft.io now needs to integrate
with it.

**Comment by cjwatson** [comment]
Can somebody please file this against [Launchpad](https://bugs.launchpad.net/launchpad/+filebug)?  We should keep this open on build.snapcraft.io as well, as I expect we'll need to expose a slightly different API for it to use once Launchpad is calculating the correct set of architectures, but the bulk of the remaining work lives in Launchpad and should be tracked there.

**Comment by cjwatson** [comment]
The Launchpad parts of this are almost finished, and I'm working on the build.snapcraft.io parts now.  However, I need a small amount of design input.  @matthewpaulthomas, could you have a look over the following and indicate how this should be presented?  Let me know if anything here is unclear.

This task calls for honouring metadata in `snapcraft.yaml` that indicates, among other things, which architectures a snap should be built for.  As a result, before it can dispatch builds, Launchpad has to consult the relevant code hosting service - in this case, GitHub - to fetch `snapcraft.yaml`.  But having HTTP request handlers that block while they go off and talk to some other service for an indefinite period of time is generally bad news; so the operation of requesting builds has to turn from synchronous HTTP requests ("request build for this snap on this architecture", which inserts a row directly into the Launchpad database) into asynchronous HTTP requests ("request all necessary builds for this snap", which schedules a job that consults GitHub, parses `snapcraft.yaml`, inserts database rows, and makes webhook deliveries back to build.snapcraft.io to indicate that it's done so).

The asynchronous operations here should normally only take a couple of seconds, but we can't guarantee that: for instance, our job runners might be backlogged, or GitHub might be slow.  It's also possible for the asynchronous operations to fail: for instance, GitHub might be down, or the repository's `snapcraft.yaml` might be malformed.

From the user's point of view, when a build was requested (either by finishing initial configuration of the repository in BSI, by using "Build manually now", or automatically because the poller script noticed a commit to the relevant branch in their GitHub repository), the next change in the UI would previously have been that new rows would appear on the repo page, one for each architecture being built.  After this change, we should instead indicate in some way that their request is in progress, so that it doesn't look like the site is ignoring them.  If their request fails, we should tell them why.

My initial proposal would be to do something like this, although of course please do suggest something else if it seems better:

 * Show pending and recently-failed build requests in the "Latest builds" and "Previous builds" tables, sorted chronologically.
   * Should a pending build request cause the most recent set of actual builds to move down to "Previous builds", or should that only happen once the actual build rows show up?
   * I think it makes sense to present build requests in the same table as builds; anything else seems too fussy, and the "Build trigger" (apparently not in the design spec?) and "Result" columns still make sense more or less as-is.  The "Architecture" and "Duration" columns should probably just be empty.  What about "Number"?  Build requests do have an ID, but it isn't from the same sequence as builds, so that could be confusing; but in the case of a failed request it probably does make sense to show the ID in some way because it's what we'd need to investigate the failure.
   * Exactly how should failed build requests be presented?  We don't have a build log to link to in this case, but we do have an error message that we could show.  (Nothing else in the builds tables currently shows error messages.)
 * For the time being, don't show completed build requests.  In the longer term, they would be useful: we could group builds under their originating request, which would essentially be part of the implementation of build sets (see e.g. #902 and #983); but that's a larger chunk of work and we don't need to tackle it as part of this.

**Comment by matthewpaulthomas** [comment]
> Should a pending build request cause the most recent set of actual builds to move down to "Previous builds", or should that only happen once the actual build rows show up?

That’s a tricky question. One objective of the “Latest builds” table is to highlight whether the developer needs to fix anything in the repo (a compilation error, for example, or trying to build on an inappropriate architecture). If the build request failed because the snapcraft.yaml is malformed, that’s something you need to fix, so I’d think that failure should occupy the “Latest builds” table, pushing previously-requested builds out. But if the build request failed because GitHub or Launchpad was down, that isn’t something the developer needs to fix, so then I’d prefer to keep the latest completed builds in the “Latest builds” table.

Is it practical to distinguish between those two types? If not, is one type much more common than the other?

> What about "Number"? Build requests do have an ID, but it isn't from the same sequence as builds, so that could be confusing; but in the case of a failed request it probably does make sense to show the ID in some way because it's what we'd need to investigate the failure.

How long is a build request ID? If it was prefixed with “Request ”, would it fit in the current column width?

> Exactly how should failed build requests be presented? We don't have a build log to link to in this case, but we do have an error message that we could show. (Nothing else in the builds tables currently shows error messages.)

How long is a typical error message of this kind? Can you provide an example?

**Comment by matthewpaulthomas** [comment]
@cjwatson Ok, [how about this](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.52a7t6trm6ee):
> The “Latest builds” table should describe, for each of the last-known-specified architectures, the latest requested build in that architecture, whether or not it has completed or even started.
> - If it has not yet started, the “Number” cell should contain only “Requested”.
> - If the request failed, the table should collapse to one row, with the “Architecture”, “Duration”, and “Result” cells merged to display the request ID and error message, for example, “(Request #11858014) Can’t find snapcraft.yaml in https://github.com/example/test master”.

This assumes that you don’t need to see a request ID unless the build request actually fails.
