### ISSUE TITLE
[landing] Welcome text seems too close to banner image

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#568]
On landing page signed in user sees "Hi" welcome text instead of the button under top banner.

This text seems to close to the image.

<img width="1052" alt="screen shot 2017-03-31 at 13 06 38" src="https://cloud.githubusercontent.com/assets/83575/24547984/0483e968-1613-11e7-80fa-a8a03f4edda3.png">

**Comment by bartaz** [comment]
@jamiedawsonyoung Could you define some spacing for it?

**Comment by kwm14** [comment]
Hi @bartaz the Vanilla team are currently working towards a new type scale which will resolve padding issues between headings and body copy in the future.

But for the time being if we add padding of 20px in-between heading and body copy that would work.

### Updated visual
![001-build snapcraft-hero](https://cloud.githubusercontent.com/assets/17748020/25619194/e9f99bb8-2f41-11e7-9133-292136fa276e.png)

**Comment by matthewpaulthomas** [comment]
That would be an improvement, but it’s still much closer to “Built automatically” than “Push to GitHub” is, making it look like they’re connected when they aren’t.

More strangely, both the current and proposed positions are much closer to “Built automatically” than the “Set up in minutes” button is:
![ ](https://cloud.githubusercontent.com/assets/19801137/26577820/9a83d658-4525-11e7-9245-ec99799bd4db.gif)

The button can get away with being that close to “Built automatically” because the strong background color walls it off from the text above. “Hi Name, let’s check out your repos” doesn’t have such a background, so it should be _at least_ as far away as the button is — not nearer.

**Comment by richmccartney** [comment]
@kwm14 I'll update this as I am working on amending the copy for this area. 

In regards to positioning, in my experience keeping placement consistency of interactions such as buttons and text help the user far more than being separate. This was a big area of UX and accessibility the team solve when working on the MAAS UI. 

After talking to @Greggless I think it would be advised to have the message in the same place and possibly similar styling so returning users. But this could be an exploration aside from this issue.
