### ISSUE TITLE
[landing] Fix the alignment of the bulleted list

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#656]
The layout of the bulleted list on [the front page](https://build.snapcraft.io) feels off-centre, which is jarring:

![bulleted list](https://assets.ubuntu.com/v1/0534f3f6-bulleted-list.png)

However, this should not be solved in an ad-hoc fashion - it should fit either be updated to use an existing pattern or formally define a new pattern.

@yaili should be consulted.

**Comment by kwm14** [comment]
Looking at the current design it looks jarring due to the short feature list and it's using the 2-col layout. My proposal would be:

- to use 3-col layout and make use of the space we have
- update grey tick icons to green tick (as seen on maas and juju websites for consistency)

### Updated iteration
![001-build snapcraft-bullet-list](https://cloud.githubusercontent.com/assets/17748020/25624270/c88dfd2a-2f50-11e7-808f-71998b11fff2.png)

Thoughts? @carlaberkers @matthewpaulthomas @nottrobin

**Comment by matthewpaulthomas** [comment]
The three-column layout was implemented as mocked up by @kwm14 above.
