### ISSUE TITLE
Organisations: "My repos" dashboard: Empty state [1]

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/build.snapcraft.io#657]
As discussed in the workshop, we should design an "empty" state for the "My repos" dashboard page (`https://build.snapcraft.io/user/{username}`) - which anyone will see if they have no added repositories, unless it's their first time.

This page will be shown when a user:

- Hits "cancel" on the "Add repositories" list, with no added reposories
- Deletes their last repo from BSI
- Has their last organisation repository deleted by someone else

Crucially, an *existing* user returning to the site should be shown this empty page rather than the "Add repositories" list. (@carlaberkers please confirm this last point).

**Comment by carlaberkers** [comment]
that sounds right @nottrobin.

The action to add a repository is the main thing people need to do, so that action should be most prominent.

**Comment by kwm14** [comment]
@carlaberkers @matthewpaulthomas do you have a wireframe of this screen?

As I wasn't in the workshop you attended it would be great to have a reference to go by for visual. 

Thanks.

**Comment by matthewpaulthomas** [comment]
@kwm14 Working on that now…

**Comment by kwm14** [comment]
Thanks @matthewpaulthomas 

I've explored a few versions based on your wireframes and taking inspiration from recent 'empty state' designs created for MAAS.

- 001 - just text
- 002 - text with infographic
- 003 - text with infographic/alert

### 001
![01-my-repos-empty-state-text](https://cloud.githubusercontent.com/assets/17748020/25665187/ba76cfcc-3014-11e7-9a72-98508acc6f0c.png)

### 002
![02-my-repos-empty-state-infogrpahic](https://cloud.githubusercontent.com/assets/17748020/25665185/ba7065ce-3014-11e7-86da-a65fc364b5fe.png)

### 003
![03-my-repos-empty-state-infogrpahic](https://cloud.githubusercontent.com/assets/17748020/25665186/ba73852e-3014-11e7-9561-4fc535252082.png)

**Comment by matthewpaulthomas** [comment]
Thanks!

If we were to have an icon, I don’t think it should be a folder: we’re integrating with GitHub, which uses a folder icon to refer to a directory inside a repo, not for a repo itself.

For a repo, GitHub uses a forked-path diagram for a personal fork, and a bookmarked book for someone else’s repo that you contribute to. That distinction isn’t relevant for the purpose of an empty state. So maybe in this case we just shouldn’t have an icon at all.

**Comment by kwm14** [comment]
@matthewpaulthomas That's a fair point. We don't want to confuse users so let's go with just text-only option.

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.5c3e9xiupuq5).

**Comment by bartaz** [comment]
I think there must have been some misunderstanding in the scope of this issue or change after it was estimated.

Current estimate [1] is enough to cover the UI part of the task - showing empty my repos table.

But currently we have no easy way to tell the difference between new user and user who has no repos (because all are removed).

As far as I remember from the workshop discussion we concluded that first time user (in a same way as new user) will be shown empty My repos table and only "Add repos" will lead them to select repos screen. The same understanding was likely the reason to close #665.
We don't have to implement anything new only if we treat new users and users with no repos in the same way.

Current spec suggests that we need to behave differently for new users (who never had any repo) and users who did have some repos but don't have anymore.

In theory we have data to tell if user is signing in for the first time, but it's currently only used for metrics, so we would need to decide if it's ok to expose it also to client app.

This would also increase the estimate, but I'm currently not sure how much without digging into more details.

FYI: @nottrobin @cjwatson @magdalena-mirowicz @matthewpaulthomas

**Comment by matthewpaulthomas** [comment]
From @cjwatson’s description in #665, the “No repos present…” part was implemented, but the “…and none added in the past” was not. So, either #665 should be reopened, or there should be a separate report for implementing “…and none added in the past”.

However, that does not need to block implementation of the empty state. Right now if you have no repos, you’re not experiencing #755, and you click “Cancel” in the Add dialog, the dialog closes and immediately reopens. Fix that, showing the empty state instead, and we’ll have made progress.

**Comment by bartaz** [comment]
@matthewpaulthomas I added #780 to implement specifically the “…and none added in the past” part.
