### ISSUE TITLE
Update dropdown layout My Repos table

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#686]
Layout of My Repos dropdowns should be updated.

<img width="595" alt="screen shot 2017-04-25 at 13 26 19" src="https://cloud.githubusercontent.com/assets/83575/25383141/02c1e010-29bb-11e7-829c-3407c916be35.png">
<img width="602" alt="screen shot 2017-04-25 at 13 26 34" src="https://cloud.githubusercontent.com/assets/83575/25383140/02c1677a-29bb-11e7-8c8a-619cfe5cc069.png">
<img width="591" alt="screen shot 2017-04-25 at 13 26 42" src="https://cloud.githubusercontent.com/assets/83575/25383142/02c7ad92-29bb-11e7-9d3d-5c9a67f5dca5.png">

**Comment by magdalena-mirowicz** [comment]
@bartaz could you add estimate in brackets please? thanks

**Comment by matthewpaulthomas** [comment]
I’m really sorry, but this is the first time I’ve seen these mockups, and the layout is quite strange in all of them. Where did they come from?

They improve on the mockups currently in the spec in one way: they show how to visually connect the clicked cell and the revealed panel (implemented in #321).

However, unless the layout changed depending on window width, they would all work poorly on phones, tablets, and narrow windows, for various reasons:
- the first two, because they assume that the buttons can fit alongside the form;
- the third, because it assumes that the warning messages can fit alongside the form.

Least importantly, I’m not a fan of putting a divider line between the form and the buttons (#754), but these layouts are incompatible with doing that.

@bartaz, would it be okay to change just the button style for now, and leave the layout for later?

**Comment by bartaz** [comment]
@matthewpaulthomas Thanks for comment.

When I started to implement the layout changes I also noticed some inconsistencies and edge cases with different text lengths, so it would actually be really helpful to only do button styles now and postpone layout changes till later once they are improved.

**Comment by bartaz** [comment]
It's probably not going to be implemented in this form.

If we will update the table styles we will more likely use the vanilla pattern styles.
