### ISSUE TITLE
Visual update of 'Missing repos' info in Add repos

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#715]
Follow-up to #680 (implemented in #713).

Popover/dialog about missing repos needs visual design and proper implementation in place of quick reuse of popover 'tooltip'.

Spec defines UI for Add repos as scrollable dialog: https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q

But we don't have visual design for that and it needs to be implemented before 'Missing repos' info can be moved into dialog popover as defined in spec.

**Comment by kwm14** [comment]
## Updated iteration

- adding new popover/dialog view

### 001 Missing repos

![updates-02-add-repos-some-selected-dialog](https://cloud.githubusercontent.com/assets/17748020/25799744/29fd0484-33de-11e7-80f8-6205bfb973e0.png)

**Comment by magdalena-mirowicz** [comment]
@kwm14 @matthewpaulthomas please chat that through

**Comment by matthewpaulthomas** [comment]
@kwm14 As we just discussed, that is rather different from the wireframe, where the list of suggestions _replaces_ the list of repos inside the dialog. I proposed that for four reasons:
- So that the suggestions have exactly the same layout for “Any missing?” as they do in the empty state.
- So that on small screens, we don’t need to use horizontal space for a border/shadow/margin conveying that there’s a popover on top of the dialog (since there is no popover).
- So that on small screens, it’s obvious that the list of suggestions scrolls (since it’s replacing a list that scrolls).
- Least of all, because all else being equal, two layers is simpler than three.

A benefit of your design, though, is that if someone clicked “Any missing?” by accident, it’s clearer how to get from the suggestions back to the list of repos. Clicking an X is more obvious than clicking anywhere outside the suggestions.

Ideally we can find a design that combines these advantages. For example, maybe “Any missing?” when you’re viewing the list could change to “Return to list” when you’re viewing the suggestions.

**Comment by matthewpaulthomas** [comment]
Work in progress:
![add repos at different screen sizes](https://cloud.githubusercontent.com/assets/19801137/26113411/5fb9fbca-3a52-11e7-8f87-45da126e05f1.png)

**Comment by kwm14** [comment]
## Updated visual

- referencing @matthewpaulthomas wireframes above
- some visual styling different to wires to fit inline with Vanilla/current patterns

### Desktop 
![new-01-add-repos-selected-desktop](https://cloud.githubusercontent.com/assets/17748020/26157044/0d5a7026-3b10-11e7-860f-87c765a86d64.png)

### Tablet
![new-02-add-repos-selected-tablet](https://cloud.githubusercontent.com/assets/17748020/26157220/97ad3baa-3b10-11e7-81cb-2f4f5ccc63b9.png)

### Mobile
![new-03-add-repos-selected-mobile](https://cloud.githubusercontent.com/assets/17748020/26157327/d6cc0eba-3b10-11e7-8382-bd04850cf798.png)

**Comment by kwm14** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[snapcraft] Add repos](https://trello.com/c/8FMcvWoJ/918-snapcraft-add-repos)

**Comment by kwm14** [comment]
## Updated visual w/missing repo modal

- disable 'add' button once new view is present
- 'return to repo list' takes users back to 'Add repos' table view

### Desktop - 1400x900
![new-01a-add-repos-selected-desktop](https://cloud.githubusercontent.com/assets/17748020/26206116/cd0aa5f0-3bdb-11e7-8457-d7df70d39cfc.png)

### Mobile - 375x667
![new-03-missing-repo-mobile-dialog-in-situ](https://cloud.githubusercontent.com/assets/17748020/26206122/d464cefc-3bdb-11e7-96cb-22b30227099e.png)

**Comment by matthewpaulthomas** [comment]
Thanks Karl!

Sorry I wasn’t clear in describing the behavior of the “Add” button. It should not be disabled *because* the suggestions view is shown. It should be disabled whenever zero repos are selected. That will *usually* be the case when the suggestions view is shown. (You probably went there because none of the repos you want are visible.) But it won’t be the case when you have “2 selected of 73 repos”.

Even with the text changed to “Return to repo list”, I still think we should have the tail pointing to it from the suggestions view, as in the original wireframe:
![choose repos to add - any missing tail](https://cloud.githubusercontent.com/assets/19801137/26242990/38983f20-3c82-11e7-8b3f-f409f9121824.png)

I’ve reported the vertical button stacking as [vanilla-framework #1079](https://github.com/vanilla-framework/vanilla-framework/issues/1079).

**Comment by kwm14** [comment]
## Updated visual w/missing repo modal

- updates to @matthewpaulthomas feedback
- 'add' button active
- tail pointer added to dialog

### Desktop - 1400x900
![new-01a-add-repos-dialog-desktop](https://cloud.githubusercontent.com/assets/17748020/26348782/b75c4aa6-3fa5-11e7-8843-ca713fd0d1ae.png)

### Mobile - 375x667
![new-03-missing-repo-mobile-dialog-in-situ](https://cloud.githubusercontent.com/assets/17748020/26348783/bc7244fa-3fa5-11e7-90bf-ee3cdf408541.png)

**Comment by matthewpaulthomas** [comment]
There are a few small glitches remaining:
- It’s desirable for the dialog to leave the “Let’s get started!” visible above, but there’s no point in leaving the site footer visible below, and once #400 is fixed the empty-state text will have pushed the footer off-screen anyway.
- It’s very strange that the buttons are more than twice as wide on narrow screens as on wide screens — reported as [vanilla-framework #1079](https://github.com/vanilla-framework/vanilla-framework/issues/1079).
- “X selected of Y repos (…)” should be right-aligned — because, though this causes wobbling with “Any missing?” vs. “Return to repo list”, it avoids wobbling in the much more common event that “73 repos” becomes “1 selected of 73 repos”. (I’ve fixed that myself in the mockups.)

I’m also concerned that the page background, the dialog fixed area background, and the dialog scrolling area background, are all exactly the same color, but I guess that’s another Vanilla thing. Apart from that, this looks good to go, thanks @kwm14. [Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q).
