### ISSUE TITLE
Add divider line between feedback message and action buttons

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/build.snapcraft.io#754]
### Current result
![repos-to-build-current](https://cloud.githubusercontent.com/assets/17748020/25954968/c69aacbe-365f-11e7-8daf-9b4d7b5a9d00.png)

### Expected result
![repos-to-build-expected](https://cloud.githubusercontent.com/assets/17748020/25954976/cdcaf44e-365f-11e7-81d8-144f58575e4b.png)

**Comment by matthewpaulthomas** [comment]
This is something Jamie and I had discussed occasionally.

It’s less noisy to convey separation with spacing rather than with dividers. Most current platforms use spacing, rather than dividers, to separate the button area from the rest of a dialog. [Gnome used to use a divider for this in some dialogs](http://mobile.osnews.com/img/1280/gnome3.jpg), but no longer does. Windows 10 uses a divider in the rare case [where a dialog has a “footnote area” below the “command area”](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742499(v=vs.85).aspx).

Using a divider would be especially tricky for us here, in that the dialog is inside a table. So a divider that stretches nearly all the way across the table would risk making the button area look more like a separate table row.

**Comment by kwm14** [comment]
In MAAS we use the divider lines across the whole web application to separate content and actions, especially in table rows when an interactive panel/dialog is presented. But in some cases MAAS has notification/feedback messages as seen above, to solve this we have in-line feedback styling which could work in this instance. 

### In line feedback
![in-line-feedback](https://cloud.githubusercontent.com/assets/17748020/26101455/26293c46-3a29-11e7-895d-9ae4c28f6acc.png)

**Comment by bartaz** [comment]
@kwm14 In our case text we show with the action often depends on the state of the given repo, so even when it seems to be short for one repo, for the same actions it can be longer in other repo.

So when designing inline actions please make sure to cover the cases when copy text is longer and would not fit in one line with actions (and may even need to wrap):
<img width="1059" alt="screen shot 2017-05-16 at 13 33 52" src="https://cloud.githubusercontent.com/assets/83575/26104012/58e84f60-3a3c-11e7-8e0e-5b5a935517d9.png">

**Comment by matthewpaulthomas** [comment]
Not doing this for the reasons discussed above: it’s needless and inconsistent noise. If form text or controls are too far horizontally from the commit buttons, we can fix that by setting a max-width for the form, rather than by adding another visual element. And if form text or controls are too close vertically to the commit buttons, we can fix that with spacing, rather than with a divider.
