### ISSUE TITLE
Daily builds instead of "build on commit"

### ISSUE THREAD

**Issue by tvansteenburgh** [canonical-websites/build.snapcraft.io#826]
I'd like to have a "build daily" option instead of just the implicit "build on commit".

In my case, I'm building snaps for etcd, but my snapcraft.yaml is not in the upstream repo (yet). So while the upstream repo has new commits daily, my snapcraft repo rarely has new commits. But I would still like to trigger a daily build of the snap.

Maybe there's a better way to solve this? I know the ultimate solution is to get the snapcraft.yaml upstream, but that can take some time. Surely I'm not the only one with this predicament?

**Comment by evandandrea** [comment]
Correct, you're [not the only person to ask for this](https://forum.snapcraft.io/t/how-to-trigger-builds-on-launchpad-upon-upstream-repository-update/643).

I think we should be careful about what behaviour we make easy. There is considerable benefit in snap building being triggered from upstream.

**Comment by evandandrea** [comment]
We've decided to implement this. The default behaviour will be daily builds, with an post-setup option to create a webhook for builds on commit.

**Comment by matthewpaulthomas** [comment]
Quick survey of the design required, as I understand it:
- Front page: small change to the workflow diagram
- “Add repos” dialog: remove the “Don’t have admin permission?” item
- “My repos”: maybe soften “Not configured”, “Error”, and “Name mismatch” text to reflect that you might have fixed the problem, but we just haven’t noticed yet
- Repo page: UI to switch between daily and on-commit builds
- Repo page: text to tell you when the next build will be

It might also make sense to make this dependent on manual rebuilds (#770), so that you can test a build fix without having to wait nearly a day for it (or switch temporarily to on-commit builds).

**Comment by matthewpaulthomas** [comment]
Also:
- Describe the new behavior when you first add a repo. If you don’t add a snapcraft.yaml, for how many hours/days/weeks/months should BSI poll to see whether you have yet?

**Comment by evandandrea** [comment]
>If you don’t add a snapcraft.yaml, for how many hours/days/weeks/months should BSI poll to see whether you have yet?

∞, with email reminders.

>It might also make sense to make this dependent on manual rebuilds (#770), so that you can test a build fix without waiting nearly a day for it.

Agreed.

**Comment by bartaz** [comment]
As daily builds work is currently in progress (other issues mentioned above) I guess we could close this one.

**Comment by elopio** [comment]
@evandandrea do you mean that the commit hook has to be manually enabled? I think that the default behaviour should be to have the commit hook enabled. That's how we catch tags and releases.

For example, I have a project with `version: git`, and today I release a new tag `v1.0`. Right after the release, I resume landings, so by the time the daily job in build.snapcraft.io runs, it's likely that I will have v1.0+a few commits in my master branch. Of course, to solve it for future tags I just have to get here and enable the builds on commit. But I already lost the window to have it done for me automatically for v1.0. I would have to wait a couple of weeks until I release v1.1 to make a snapcraft stable release. Or I would have to manually edit my snapcraft.yaml to have `source-tag: v1.0`, commit that to master, and then revert the commit.

If this is not default, I imagine a lot of people missing the first stable release of their branch, and having to do this dance. 

Travis allows this option: run on every commit, and run nightly only if no commit has happened on the last 24h. That sounds like the right setup for all my snaps. I'm not sure why somebody would like something different.

**Comment by evandandrea** [comment]
@elopio no, I’m saying the default behaviour of setting up build.snapcraft.io will be daily builds (at most one build per day, if and only if your code or part dependencies change). There will be a UI option to switch to builds on commit.

**Comment by elopio** [comment]
@bartaz This is feature is not yet available, right? I think it would be better to keep this issue open until it the feature is done.

**Comment by bartaz** [comment]
@elopio If I'm not mistaken (status could change from late November when it was released) so called 'daily builds' but to be more precise 'build on dependency change'. Meaning that build will be triggered if a GitHub repository listed as a dependency in `parts` section changed.
So it runs daily but only if any dependency changed. It will not build daily if nothing changed.

So in theory feature is available, but currently it only works for dependencies being repositories on GitHub, because that's where we can easily detect if anything changed in last 24h.

**Comment by elopio** [comment]
@bartaz oh, I think that will work for me!
