### ISSUE TITLE
Show number of user repos in 'Add repos' footer

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#832]
<img src='https://cloud.githubusercontent.com/assets/17748020/26157044/0d5a7026-3b10-11e7-860f-87c765a86d64.png' />

In 'Add repos' footer we currently only show the number of selected repos, as per design we should show `X selected out of Y repos`.

**Comment by bartaz** [comment]
The issue with this feature is that we may not know the exact number of repos user has (if they have more then one page or repos).

GH doesn't give us exact number of repos user has (especially that listing also consist of organisation repos), we only know how many pages of repos user has.

To know the exact number we would need to load all the pages of repos first.

So the question is - what to show before we know how many repos user have?
- do we want to show this number at all?
- do we want to show it only when we loaded all repos?
- do we want to gradually increase the number when we load subsequent pages?

**Comment by matthewpaulthomas** [comment]
[Spec updated](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.1uxwfvh1rvjz): “If the exact number of repos is not known because GitHub reports only the number of batches and not all have been loaded, the number should be reported as “about {total}”, where total = (number of batches – 0.5) × the batch size.”
