### ISSUE TITLE
Compare design of other Vanilla patterns in BSI

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#881]

**Comment by bartaz** [comment]
### Vanilla headings

1. Headings in BSI have 'align' property, it's used on landing page to center. Heading pattern from Vanilla does not include align styles. Align in Vanilla is possible via additional utility classes (`u-align--center`). -- Likely we can workaround this limitation in our implementation of headings.

2. Landing page has custom spacing and overrides margins of all the headings to same value of 3rem. -- To update headings on landing page to Vanilla we would either need to still override their margins or update whole layout of landing page to use Vanilla grid and vertical rhythm.

**Comment by bartaz** [comment]
### List

1. The only place where we used to have Vanilla list style is on landing page, but it was changed from (Vanilla) grey ticks to custom (green) ticks.

BSI landing page:
<img width="1010" alt="screen shot 2017-07-11 at 14 37 49" src="https://user-images.githubusercontent.com/83575/28068624-a2756bfa-6646-11e7-8062-ae033ba43259.png">

Vanilla:
<img width="492" alt="screen shot 2017-07-11 at 14 38 10" src="https://user-images.githubusercontent.com/83575/28068630-a5ab1f22-6646-11e7-860e-69d0f6f7edf7.png">

We could either:
- get back to using grey ticks on landing page
- propose new (green) ticks to Vanilla
- keep using custom list on landing page (as it's still the only place where we use this pattern)

**Comment by bartaz** [comment]
### Notification

1. Notification is identical stylewise, but BSI notification has 'Dismiss' icon, while Vanilla only allows inline text action
<img width="1045" alt="screen shot 2017-07-11 at 14 43 37" src="https://user-images.githubusercontent.com/83575/28068804-5ce563b4-6647-11e7-8170-5a2f753c67c3.png">


We could either:
- Use Vanilla notification (with Dismiss link rather than icon) - but it's likely to look bad because we already have another (feedback) link in notification
- Have custom notification component what uses Vanilla style, but also has dismiss icon
- Propose Vanilla update to allow having a dismiss icon in notificaion

**Comment by bartaz** [comment]
### Card

We used to have a Card pattern in Add repos (dialog), because it has the same border style, but we don't anymore. Add repos dialog is similar, but Card pattern has a padding which Add repos dialog doesn't have.

BSI (we don't have padding because list spreads from border to border):
<img width="958" alt="screen shot 2017-07-11 at 14 47 56" src="https://user-images.githubusercontent.com/83575/28068986-13a59fce-6648-11e7-9edd-489d0521f780.png">

Vanilla (padding inside card):
<img width="1042" alt="screen shot 2017-07-11 at 14 48 35" src="https://user-images.githubusercontent.com/83575/28069005-29e0087e-6648-11e7-86ba-eb0ee6b19f25.png">


We could:
- propose adding option to Vanilla Card pattern to remove padding from card
- keep using custom styles and remove not used Card pattern component

**Comment by matthewpaulthomas** [comment]
> we used to have Vanilla list style … on landing page, but it was changed from (Vanilla) grey ticks to custom (green) ticks

I think the Vanilla `.is-ticked` list bullet ![vanilla list bullet](https://user-images.githubusercontent.com/19801137/28071446-dd986236-6647-11e7-9ffb-249556d3cceb.png) is misleading because it looks needlessly similar to an iOS WebKit checkbox. ![ios webkit checked](https://user-images.githubusercontent.com/19801137/28071564-329c0a62-6648-11e7-935e-ad8f67860ec2.png) I’ll request that this be changed in Vanilla.

> Add repos dialog is similar, but Card pattern has a padding which Add repos dialog doesn't have.

A dialog is fundamentally different from a card. One way to recognize this is that dialogs could *contain* cards. (Even if you think the items in this example aren’t quite cards, it’s easy to imagine that they could be.)

![google docs dialog in card view](https://user-images.githubusercontent.com/19801137/28071819-0538b5ce-6649-11e7-9662-bc149ba894b9.png)

Dialogs also have differences in behavior — such as modality, scrolling, and [resizing](https://github.com/canonical-websites/build.snapcraft.io/issues/829) — which could be more easily handled if they are distinct from cards at the code level.
