### ISSUE TITLE
Investigate whether we can ask for admin perms later

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#904]
In switching to daily builds by default, we can ask users who want per-commit builds to manually set up a webhook. We should explore whether it's possible to go beyond this and set it up for them, presumably going back through the GitHub permissions request.

**Comment by nottrobin** [comment]
This is probably related to #906, as in that will help us understand what our options are for controlling GitHub permissions.

**Comment by bartaz** [comment]
I can't find the means to ask for changing permissions later or to revoke some permissions after we use them.

For sure it's not possible with OAuth and quite likely not possible with GH Apps as well.

One thing I noticed (compared to Travis for example) is that we ask for `admin:repo_hook` while we possibly only need `write:repo_hook` (Read-write access to repo webhooks). `admin:repo_hook` permission allows to delete webhooks, but we don't use it.

So using `write:repo_hook` should be enough for us to set up webhook in a users' repos (they still need to be admins of given repo), but we will not prompt for "admin" access at point of login, so GH login will ask for "Read-write":

<img width="504" alt="screen shot 2017-08-10 at 09 50 10" src="https://user-images.githubusercontent.com/83575/29160177-9058043c-7db1-11e7-8d53-b237ee0c3642.png">

instead of "Admin":

<img width="507" alt="screen shot 2017-08-10 at 09 49 51" src="https://user-images.githubusercontent.com/83575/29160197-9df70c14-7db1-11e7-9c18-f3874928b9bc.png">

This can hopefully look less scary to users that don't want to give us admin access to anything.

Note that to create a webhook on a repo user needs to be an admin of it, so this restriction will still apply, but it's only visible at the point of adding a repository. We cannot add repository user is not admin of (because we cannot add webhook). If we implement daily builds this restriction will not apply, because we will not need to set up webhook to add a repo. Only to set up a webhook user needs to be an admin. We can show users how to set up webhook themselves, but it doesn't change the fact that they need to be admins to do it anyway.
