### ISSUE TITLE
Investigate moving to GitHub Apps

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#906]
It allows you to filter down the set of repositories you grant access for, and with finer grained permissions (you can ask for a permission to just snapcraft.yaml):
https://youtu.be/o_MBuszB39M?t=40m5s

https://developer.github.com/apps/building-integrations/

**Comment by nottrobin** [comment]
This may help to solve #904

**Comment by bartaz** [comment]
### Permissions:

GitHub Apps (as advertised) seems to have much more granular permissions allowing to define a very limited set of permissions required by the app.
But these are defined by App creator when app is registered on GitHub and I couldn't find any documented way to change that (for example request more permissions temporally) later by user.

With GitHub Apps we would not need to request additional permissions to create webhook, because GH App has a built in webhook where various events are sent.
In our case that would mean that instead of asking for `admin:repo_hook` (or `write:repo_hook` that we probably should use instead as mentioned in #904) we would ask for read only Repository Push permissions, to know when commits are pushed to a branch:

<img width="747" alt="screen shot 2017-08-10 at 16 15 49" src="https://user-images.githubusercontent.com/83575/29174660-3f1b27d0-7de7-11e7-95d1-297ec446a6e1.png">

This would possibly remove any need for admin/write permissions on our side, because we would not need to add webhooks to repos. GH App will have its own webhook where repo events will be sent.

Other possibly interesting option is asking for single file access (snapcraft.yaml in our case).
The issue with that is currently that when registering an app you are only allowed to specify ONE path to request access to while currently we support 3 possible locations of snapcraft.yaml.

<img width="745" alt="screen shot 2017-08-10 at 16 19 34" src="https://user-images.githubusercontent.com/83575/29174818-bcfe7ba2-7de7-11e7-9bf1-36ddf55afb36.png">

### Implementation:

From the docs it seems that implementation of GitHub App (how it authorises with GH, how it calls APIs on its behalf, etc) is significantly different from what we currently have with OAuth meaning that significant amount of time would need to be invested into changing different parts of the BSI (how users log in, how it communicates with GH, how we receive and interpret data from webhook, and possibly many more). It's hard to estimate the effort at this point (as many parts of the implementation details are not clear and we would need to make some proof of concept first to try it out), but it seems to be more than one iteration (2 weeks) time.

Even from developer point of view GitHub Apps are a bit confusing at this point.
With OAuth it's quite clear that user signs into given app with their GH account and authorises the app. GH App on the other hand is meant to be installed to GH account (user or org) and then used via this 'installation'. Which is not clear to me how it works from user perspective.
I tried installing some apps from Marketplace (Travis, Circle CI, etc), but they all ended up working in old fashioned OAuth way in the end (from the docs it seems that to identify users in the app OAuth is used anyway).

It seems that GH Apps are more targeted for organizations (that could install an app to an organization account once and make it available for all its users), but I'm not sure how much benefit that is in it for single developers (that are probably used to OAuth apps anyway.

Comparison of GitHub Apps and OAuth Apps:
https://developer.github.com/apps/building-integrations/setting-up-a-new-integration/about-choosing-an-integration-type/

Identifying users in GH App (via OAuth):
https://developer.github.com/apps/building-integrations/setting-up-and-registering-github-apps/identifying-users-for-github-apps/

Registering an app:
https://github.com/settings/apps/new

### Conclusion

While moving to GH Apps has some benefits (more granular permissions, installation on organization level, built in webhook) it doesn't really help us solve the issue of defining and asking permissions first.

Also migrating to GH Apps seems to require changes to many places of our app (users log in, calling GH API, webhook support), so needs more investigation, proof of concept before final implementation.

For now it seems it may be too big implementation cost for not a significant benefit, although in a long term it may be a valuable option to consider (when GH Apps get more usage, become better known among devs).

**Comment by evandandrea** [comment]
>Other possibly interesting option is asking for single file access (snapcraft.yaml in our case) …

This would reduce the number of webhook events we received to just when the snapcraft.yaml changes, right? So even if we could add in snapcraft.yaml, .snapcraft.yaml, and snap/snapcraft.yaml, switching to this would lose us build on git push (unless the yaml changed in that push).

**Comment by bartaz** [comment]
> switching to this would lose us build on git push

@evandandrea I'm not sure about this. It's not exactly clear from the docs, but I guess that 'Git push to a repository.' permission (that is separate to 'Manage single file') means event is sent to webhook every time something is pushed to repo (even if we don't have permission to look into code to see what it is). 

It wouldn't make much sense for GH to introduce single configuration file access (for tools like travis etc) if that would not allow these tools to listen to repo pushes.

**Comment by evandandrea** [comment]
That makes sense. Digging further, it looks like the primary motivation for "manage a single file" was to [support write access to a single file](https://platform.github.community/t/single-file-write-access/374).
