### ISSUE TITLE
Not possible to remove repo where snap name has been transferred

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/build.snapcraft.io#998]
<img width="1058" alt="screen shot 2017-11-06 at 10 00 50" src="https://user-images.githubusercontent.com/1523179/32420103-97407f14-c2d9-11e7-9801-49bfb12b27d5.png">
<img width="1048" alt="screen shot 2017-11-06 at 10 01 45" src="https://user-images.githubusercontent.com/1523179/32420104-9786b75e-c2d9-11e7-89d6-48be47e9bec3.png">

Originally gogland was registered to the snapcrafters SSO account with the repo under https://github.com/snapcrafters (of which I am a member). We set up build.snapcraft.io and everything worked fine.

We then transferred gogland to the jetbrains SSO account. It is no longer possible to remove the repo from my dashboard.

**Comment by bartaz** [comment]
From what I understand it works as expected.

We wanted to prevent people from removing repos of snaps they didn't register because they can't add them back. So if you don't own the name of the snap in the store - you cannot remove it.

But in such particular case of snap being transferred this feature 'backfires', because it prevents you from removing a repo/snap that was moved to new owner (because you don't own it anymore).

We can remove it manually from database and launchpad, but this obviously wont prevent this from happening in future.

To fix this we would need to remove the restriction of removing repos/snaps that user doesn't own.

My first proposal would be to instead of preventing user to remove such repo warn them that this cannot be undone (they will not be able to register this name again because they don't own this).

But I guess we need a UX input on that.

**Comment by evandandrea** [comment]
>My first proposal would be to instead of preventing user to remove such repo warn them that this cannot be undone (they will not be able to register this name again because they don't own this).

I think your proposal is sound. @matthewpaulthomas, what are your thoughts?

**Comment by matthewpaulthomas** [comment]
I’m sorry this still hasn’t been scheduled.  At a quick glance, the idea of a custom warning makes sense.
